DEFAULT_BRANDS = {
    'CHEVROLET': { 'model': 'AGILE',
				   'model': 'ASTRA',
				   'model': 'BLAZER',
				   'model': 'CAMARO',
				   'model': 'CAPTIVA',
				   'model': 'CARAVAN',
				   'model': 'CELTA',
				   'model': 'CHEVETTE',
				   'model': 'CLASSIC',
				   'model': 'COBALT',
				   'model': 'CORSA',
				   'model': 'CORVETTE',
				   'model': 'CRUZE',
				   'model': 'KADETT',
				   'model': 'MALIBU',
				   'model': 'MERIVA',
				   'model': 'MONTANA',
				   'model': 'MONZA',
				   'model': 'OMEGA',
				   'model': 'ONIX',
				   'model': 'OPALA',
				   'model': 'PRISMA',
				   'model': 'S10',
				   'model': 'SILVERADO',
				   'model': 'SONIC',
				   'model': 'SPIN',
				   'model': 'TRACKER',
				   'model': 'VECTRA',
				   'model': 'VERANEIO',
				   'model': 'ZAFIRA'
				 },
    'FIAT': { 'model': '147',
			  'model': '500',
			  'model': 'BRAVA',
			  'model': 'BRAVO',
			  'model': 'DOBLO',
			  'model': 'DUCATO',
			  'model': 'ELBA',
			  'model': 'FIORINO',
			  'model': 'FREEMONT',
			  'model': 'GRAND_SIENA',
			  'model': 'IDEA',
			  'model': 'LINEA',
			  'model': 'MAREA',
			  'model': 'PALIO',
			  'model': 'PREMIO',
			  'model': 'PUNTO',
			  'model': 'SIENA',
			  'model': 'STILO',
			  'model': 'STRADA',
			  'model': 'TEMPRA',
			  'model': 'TIPO',
			  'model': 'TORO',
			  'model': 'UNO'
    		},
    'FORD': { 'model': 'BELINA',
			  'model': 'CORCEL',
			  'model': 'CORCEL2',
			  'model': 'COURIER',
			  'model': 'DELREY',
			  'model': 'ECOSPORT',
			  'model': 'EDGE',
			  'model': 'ESCORT',
			  'model': 'EXPLORER',
			  'model': 'F-1',
			  'model': 'F-100',
			  'model': 'F-1000',
			  'model': 'F-150',
			  'model': 'F-250',
			  'model': 'F-350',
			  'model': 'F-4000',
			  'model': 'F-75',
			  'model': 'MONZA',
			  'model': 'FIESTA',
			  'model': 'FOCUS',
			  'model': 'FUSION',
			  'model': 'GALAXIE',
			  'model': 'JEEP',
			  'model': 'KA',
			  'model': 'KA+',
			  'model': 'LANDAU',
			  'model': 'MAVERICK',
			  'model': 'MONDEO',
			  'model': 'MUSTANG',
			  'model': 'PAMPA',
			  'model': 'RANGER',
			  'model': 'RURAL',
			  'model': 'TAURUS',
			  'model': 'TRANSIT',
			  'model': 'VERONA',
			  'model': 'VERSAILLES'
            },
    'HONDA': {'model': 'ACCORD',
			  'model': 'CITY',
			  'model': 'CIVIC',
			  'model': 'CRV',
			  'model': 'FIT',
			  'model': 'HRV'
             },
    'HYUNDAI': { 'model': 'ACCENT',
				 'model': 'ATOS',
				 'model': 'AZERA',
				 'model': 'COUPE',
				 'model': 'ELANTRA',
				 'model': 'EQUUS',
				 'model': 'GALLOPER',
				 'model': 'GENESIS',
				 'model': 'GRAND_SANTA_FE',
				 'model': 'H1 STAREX',
				 'model': 'H100',
				 'model': 'HB20',
				 'model': 'HB20S',
				 'model': 'HB20X',
				 'model': 'HR',
				 'model': 'I30',
				 'model': 'I30_CW',
				 'model': 'IX35',
				 'model': 'SANTA_FE',
				 'model': 'SONATA',
				 'model': 'TERRACAN',
				 'model': 'TIBURON',
				 'model': 'TUCSON',
				 'model': 'VELOSTER',
				 'model': 'VERACRUZ'
               },
    'MITSUBISHI': { 'model': '3000GT',
				 'model': 'AIRTREK',
				 'model': 'ASX',
				 'model': 'COLT',
				 'model': 'ECLIPSE',
				 'model': 'GALANT',
				 'model': 'GRANDIS',
				 'model': 'L200',
				 'model': 'L200_OUTDOOR',
				 'model': 'L200_SAVANA',
				 'model': 'L200_TRITON',
				 'model': 'L300',
				 'model': 'LANCER',
				 'model': 'OUTLANDER',
				 'model': 'PAJERO',
				 'model': 'PAJERO_DAKAR',
				 'model': 'PAJERO_FULL',
				 'model': 'PAJERO_IO',
				 'model': 'PAJERO_SPORT',
				 'model': 'PAJERO_TR4',
				 'model': 'RAIDER',
				 'model': 'SPACE_WAGON'                    
                  },
    'PEUGEOT': { 'model': '106',
				 'model': '2008',
				 'model': '206',
				 'model': '207',
				 'model': '208',
				 'model': '3008',
				 'model': '306',
				 'model': '307',
				 'model': '308',
				 'model': '308cc',
				 'model': '406',
				 'model': '407',
				 'model': '408',
				 'model': '508',
				 'model': '605',
				 'model': '607',
				 'model': '806',
				 'model': '807',
				 'model': 'BOXER',
				 'model': 'HOGGAR',
				 'model': 'PARTNER',
				 'model': 'RCZ'
            },
    'RENAULT': { 'model': '19',
				 'model': 'CLIO',
				 'model': 'DAUPHINE',
				 'model': 'DUSTER',
				 'model': 'DUSTER_OROCH',
				 'model': 'EXPRESS',
				 'model': 'FLUENCE',
				 'model': 'GORDINI',
				 'model': 'GRAND_SCENIC',
				 'model': 'KANGOO',
				 'model': 'LAGUNA',
				 'model': 'LOGAN',
				 'model': 'MASTER',
				 'model': 'MEGANE',
				 'model': 'SANDERO',
				 'model': 'SCENIC',
				 'model': 'SYMBOL',
				 'model': 'TRAFIC',
				 'model': 'TWINGO'
               },
    'TOYOTA': { 'model': 'AVALON',
				 'model': 'BANDEIRANTE',
				 'model': 'CAMRY',
				 'model': 'CELICA',
				 'model': 'COROLLA',
				 'model': 'CORONA',
				 'model': 'ETIOS',
				 'model': 'ETIOS_CROSS',
				 'model': 'FIELDER',
				 'model': 'FJ_CRUISER',
				 'model': 'HILUX',
				 'model': 'HILUX_SW4',
				 'model': 'LAND_CRUISER_PRADO',
				 'model': 'LEXUS',
				 'model': 'MR-2',
				 'model': 'PASEO',
				 'model': 'PREMIO',
				 'model': 'PREVIA',
				 'model': 'PRIUS',
				 'model': 'RAV4',
				 'model': 'SIENNA',
				 'model': 'TACOMA',
				 'model': 'TUNDRA',
				 'model': 'VENZA'
              },
    'VOLKSWAGEN':{ 'model': '1300',
				   'model': '1500',
				   'model': '1600',
				   'model': 'AMAROK',
				   'model': 'APOLLO',
				   'model': 'BORA',
				   'model': 'BRASILIA',
				   'model': 'BUGGY',
				   'model': 'CROSS_UP',
				   'model': 'CROSSFOX',
				   'model': 'EOS',
				   'model': 'EUROVAN',
				   'model': 'FOX',
				   'model': 'FUSCA',
				   'model': 'GOL',
				   'model': 'GOLF',
				   'model': 'JETTA',
				   'model': 'KARMANN_GHIA',
				   'model': 'KOMBI',
				   'model': 'LOGUS',
				   'model': 'NEW_BEATLE',
				   'model': 'PARATI',
				   'model': 'PASSAT',
				   'model': 'PASSAT_VARIANT',
				   'model': 'POINTER',
				   'model': 'POLO',
				   'model': 'POLO_SEDAN',
				   'model': 'QUANTUM',
				   'model': 'SANTANA',
				   'model': 'SAVEIRO',
				   'model': 'SCIROCCO',
				   'model': 'SP2',
				   'model': 'SPACE_CROSS',
				   'model': 'SPACEFOX',
				   'model': 'TIGUAN',
				   'model': 'TL',
				   'model': 'TOUAREG',
				   'model': 'UP',
				   'model': 'VAN',
				   'model': 'VARIANT',
				   'model': 'VARIANT2',
				   'model': 'VOYAGE'
                 },
    'ALFA_ROMEO': { 'model': '145',
				   'model': '147',
				   'model': '155',
				   'model': '156',
				   'model': '164',
				   'model': '166',
				   'model': '2300_TI',
				   'model': 'BERLINA',
				   'model': 'SPIDER'
                  },
    'ASTON_MARTIR': { 'model': 'DB7',
				      'model': 'DB9',
				      'model': 'DBS',
				      'model': 'RAPIDE',
				      'model': 'V12_VANTAGE',
				      'model': 'VANTAGE',
				      'model': 'VIRAGE'
				    },
    'AUDI': { 'model': '80',
			  'model': 'A1',
			  'model': 'A2',
			  'model': 'A3',
			  'model': 'A4',
			  'model': 'A6',
			  'model': 'A7',
			  'model': 'A8',
			  'model': 'ALLROAD',
			  'model': 'Q3',
			  'model': 'Q5',
			  'model': 'Q7',
			  'model': 'R8',
			  'model': 'RS_Q3',
			  'model': 'RS3',
			  'model': 'RS4',
			  'model': 'RS6',
			  'model': 'RS7',
			  'model': 'S3',
			  'model': 'S4',
			  'model': 'S5',
			  'model': 'S6',
			  'model': 'S7',
			  'model': 'S8',
			  'model': 'SQ5',
			  'model': 'TT',
			  'model': 'TT_RS',
			  'model': 'TTS'
            },
    'BENTLEY',
    'BMW',
    'CADILAC',
    'CHERY',
    'CHEVROLET',
    'CHRYSLER',
    'CITROEN',
    'DODGE',
    'FERRARI',
    'FIAT',
    'FORD',
    'GURGEL',
    'HONDA',
    'HYUNDAI',
    'IVECO',
    'JAC',
    'JAGUAR',
    'JEEP',
    'KIA',
    'LAMBORGHINI',
    'LAND_ROVER',
    'LEXUS',
    'LIFAN',
    'MASERATI',
    'MERCEDES_BENS',
    'MINI',
    'MITSUBISHI',
    'NISSAN',
    'PEUGEOT',
    'PORSCHE',
    'PUMA',
    'SMART',
    'SSANGYONG',
    'SUBARU',
    'SUZUKI',
    'TOYOTA',
    'TROLLER',
    'VOLKSWAGEN',
    'VOLVO',
    'WILLYS'
}
